// Generated by CoffeeScript 1.3.3
var page, system;

system = new System(100, 100);

page = new Page(20, 20);

system.push(page);

window.onload = function() {
  return system.draw();
};

/*
  canvas = document.getElementById('postit');
  if ( ! canvas || ! canvas.getContext ) 
    return false;
  ctx = canvas.getContext('2d');
  ctx.beginPath();
  ctx.arc(70, 70, 60, 10 * Math.PI / 180, 80 * Math.PI / 180, true);
  ctx.stroke();
*/

