// Generated by CoffeeScript 1.3.3
var Page;

Page = (function() {

  function Page(postits) {
    this.postits = postits != null ? postits : new Array;
  }

  Page.prototype.push = function(postit) {
    return this.postits.push(postit);
  };

  return Page;

})();
