// Generated by CoffeeScript 1.3.3
var Page;

Page = (function() {

  function Page(x, y) {
    this.x = x;
    this.y = y;
  }

  Page.prototype.pos = function() {
    return "x:" + this.x + ",y:" + this.y;
  };

  return Page;

})();
