// Generated by CoffeeScript 1.3.3
var Postit;

Postit = (function() {

  function Postit(x, y, text) {
    this.x = x;
    this.y = y;
    this.text = text != null ? text : 'test';
  }

  return Postit;

})();
