// Generated by CoffeeScript 1.3.3
var System;

System = (function() {

  System.margin_left = 10;

  System.margin_top = 10;

  System.power = 2.5;

  System.page_x = 20;

  System.page_y = 50;

  System.page_size_width = 210 * System.power;

  System.page_size_height = 297 * System.power;

  System.postit_size_width = 100;

  System.postit_size_height = 30;

  function System(x, y, pages) {
    var system;
    this.x = x != null ? x : 0;
    this.y = y != null ? y : 0;
    this.pages = pages != null ? pages : new Array;
    system = document.getElementById("system");
    /*  
        system.addEventListener('click',(e)=>
      #  rect = system.getBoundingClientRect()
      #postit = new Postit(e.x-System.page_x-rect.left,e.y-System.page_y-rect.top)
      #@pages[0].push postit
      #this.draw()
    ,false)
    */

  }

  System.prototype.pos = function() {
    return "x:" + this.x + ",y:" + this.y;
  };

  System.prototype.page_add = function() {
    var page;
    page = new Page(System.margin_left + System.page_size_width * (this.pages.length % 2), System.margin_top + System.page_size_height * Math.floor(this.pages.length / 2), this.pages.length + 1);
    return this.pages.push(page);
  };

  System.prototype.draw = function() {
    var canvas, ctx, key, num, page_x, page_y, postit, _results;
    canvas = document.getElementById('postit');
    if (!canvas || !canvas.getContext) {
      return false;
    }
    ctx = canvas.getContext('2d');
    ctx.beginPath();
    _results = [];
    for (key in this.pages) {
      ctx.strokeRect((key % 2) * System.page_size_width * System.power + System.page_x, Math.floor(key / 2) * System.page_size_height * System.power + System.page_y, System.page_size_width * System.power, System.page_size_height * System.power);
      _results.push((function() {
        var _results1;
        _results1 = [];
        for (num in this.pages[key].postits) {
          postit = this.pages[key].postits[num];
          page_x = (key % 2) * System.page_size_width * System.power + System.page_x;
          page_y = Math.floor(key / 2) * System.page_size_height * System.power + System.page_y;
          _results1.push(ctx.strokeRect(postit.x + page_x, postit.y + page_y, System.postit_size_width * System.power, System.postit_size_height * System.power));
        }
        return _results1;
      }).call(this));
    }
    return _results;
  };

  return System;

})();
