// Generated by CoffeeScript 1.3.3
var System;

System = (function() {

  function System(x, y, pages) {
    this.x = x;
    this.y = y;
    this.pages = pages != null ? pages : new Array;
  }

  System.prototype.pos = function() {
    return "x:" + this.x + ",y:" + this.y;
  };

  System.prototype.push = function(page) {
    return this.pages.push(page);
  };

  System.prototype.draw = function() {
    var canvas, ctx;
    canvas = document.getElementById('postit');
    if (!canvas || !canvas.getContext) {
      return false;
    }
    ctx = canvas.getContext('2d');
    ctx.beginPath();
    ctx.arc(70, 70, 60, 10 * Math.PI / 180, 80 * Math.PI / 180, true);
    return ctx.stroke();
  };

  return System;

})();
